### ISSUE TITLE
Oscillo service: redundant information

### ISSUE THREAD

**Issue by nschoe** [instar-robotics/kheops#20]
When the oscillo service is enabled, all Functions report the `OscilloData` message, which contain redundant fields:
- `period`: all Functions in a script run at the same period, so its redundant to publish it
- `warning`: it is apparently only filled for the first item, which is the RT Token.

**Comment by chewbak** [comment]
it's not a bug ... i would use the same ROS Message for rttoken display and the full oscillo

**Comment by chewbak** [comment]
I change OscilloArray message and add RtToken message
